/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author ANGEL ABARO
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.setExtendedState(frmInicio.MAXIMIZED_BOTH); // para que salga en tod la pantalla
        this.setTitle("Sistema de reserva de habitaciones y gestion de ventas - Residencia DENAF");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblamaterno = new javax.swing.JLabel();
        lblapaterno = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblacceso = new javax.swing.JLabel();
        lblidpersona = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnusisdenaf = new javax.swing.JMenu();
        mnuarchivo = new javax.swing.JMenu();
        itmnuhabitaciones = new javax.swing.JMenuItem();
        itmnuproductos = new javax.swing.JMenuItem();
        mnureservas = new javax.swing.JMenu();
        itmnureservasyconsumos = new javax.swing.JMenuItem();
        itmnuclientes = new javax.swing.JMenuItem();
        itmnupagos = new javax.swing.JMenuItem();
        mnuconsultas = new javax.swing.JMenu();
        mnuconfiguraciones = new javax.swing.JMenu();
        itmnuusuariosyaccesos = new javax.swing.JMenuItem();
        mnuherramientas = new javax.swing.JMenu();
        mnuayuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnusalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(51, 102, 0));

        lblamaterno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblamaterno.setForeground(new java.awt.Color(255, 255, 204));
        lblamaterno.setText("jLabel4");
        desktop.add(lblamaterno);
        lblamaterno.setBounds(30, 124, 80, 10);

        lblapaterno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblapaterno.setForeground(new java.awt.Color(255, 255, 204));
        lblapaterno.setText("jLabel3");
        desktop.add(lblapaterno);
        lblapaterno.setBounds(30, 94, 80, 10);

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 204));
        lblnombre.setText("jLabel2");
        desktop.add(lblnombre);
        lblnombre.setBounds(30, 64, 80, 10);

        lblacceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblacceso.setForeground(new java.awt.Color(255, 255, 204));
        lblacceso.setText("jLabel5");
        desktop.add(lblacceso);
        lblacceso.setBounds(30, 154, 80, 10);

        lblidpersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblidpersona.setForeground(new java.awt.Color(255, 255, 204));
        lblidpersona.setText("jLabel1");
        desktop.add(lblidpersona);
        lblidpersona.setBounds(30, 34, 80, 10);

        mnusisdenaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Inicio.png"))); // NOI18N
        mnusisdenaf.setMnemonic('f');
        mnusisdenaf.setText("Sistema DENAF");
        menuBar.add(mnusisdenaf);

        mnuarchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Archivo.png"))); // NOI18N
        mnuarchivo.setMnemonic('e');
        mnuarchivo.setText("Archivo");

        itmnuhabitaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        itmnuhabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/habitaciones.png"))); // NOI18N
        itmnuhabitaciones.setMnemonic('t');
        itmnuhabitaciones.setText("Habitaciones");
        itmnuhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnuhabitacionesActionPerformed(evt);
            }
        });
        mnuarchivo.add(itmnuhabitaciones);

        itmnuproductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itmnuproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/productos.png"))); // NOI18N
        itmnuproductos.setMnemonic('y');
        itmnuproductos.setText("Productos");
        itmnuproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnuproductosActionPerformed(evt);
            }
        });
        mnuarchivo.add(itmnuproductos);

        menuBar.add(mnuarchivo);

        mnureservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Reservas.png"))); // NOI18N
        mnureservas.setMnemonic('h');
        mnureservas.setText("Reservas");

        itmnureservasyconsumos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itmnureservasyconsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/reservas-consumos.png"))); // NOI18N
        itmnureservasyconsumos.setMnemonic('c');
        itmnureservasyconsumos.setText("Reservas y consumos");
        itmnureservasyconsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnureservasyconsumosActionPerformed(evt);
            }
        });
        mnureservas.add(itmnureservasyconsumos);

        itmnuclientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itmnuclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/clientes.png"))); // NOI18N
        itmnuclientes.setMnemonic('a');
        itmnuclientes.setText("Clientes");
        itmnuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnuclientesActionPerformed(evt);
            }
        });
        mnureservas.add(itmnuclientes);

        itmnupagos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        itmnupagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/pagos.png"))); // NOI18N
        itmnupagos.setText("Pagos");
        mnureservas.add(itmnupagos);

        menuBar.add(mnureservas);

        mnuconsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Consultas.png"))); // NOI18N
        mnuconsultas.setText("Consultas");
        menuBar.add(mnuconsultas);

        mnuconfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Configuraciones.png"))); // NOI18N
        mnuconfiguraciones.setText("Configuraciones");

        itmnuusuariosyaccesos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itmnuusuariosyaccesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/trabajadores.png"))); // NOI18N
        itmnuusuariosyaccesos.setText("Usuario y accesos");
        itmnuusuariosyaccesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnuusuariosyaccesosActionPerformed(evt);
            }
        });
        mnuconfiguraciones.add(itmnuusuariosyaccesos);

        menuBar.add(mnuconfiguraciones);

        mnuherramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Herramientas.png"))); // NOI18N
        mnuherramientas.setText("Herramientas");
        menuBar.add(mnuherramientas);

        mnuayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Ayuda.png"))); // NOI18N
        mnuayuda.setText("Ayuda");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Acerca de...");
        mnuayuda.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Ayuda");
        mnuayuda.add(jMenuItem4);

        menuBar.add(mnuayuda);

        mnusalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Salir.png"))); // NOI18N
        mnusalir.setText("Salir");
        mnusalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnusalirMouseClicked(evt);
            }
        });
        menuBar.add(mnusalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmnureservasyconsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnureservasyconsumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmnureservasyconsumosActionPerformed

    private void itmnuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnuclientesActionPerformed
        // TODO add your handling code here:
        frmCliente form = new frmCliente();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_itmnuclientesActionPerformed

    private void itmnuhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnuhabitacionesActionPerformed
        // TODO add your handling code here:
        frmHabitacion form = new frmHabitacion();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_itmnuhabitacionesActionPerformed

    private void itmnuproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnuproductosActionPerformed
        // TODO add your handling code here:
        frmproducto form = new frmproducto();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_itmnuproductosActionPerformed

    private void itmnuusuariosyaccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnuusuariosyaccesosActionPerformed
        // TODO add your handling code here:
        frmtrabajador form = new frmtrabajador();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_itmnuusuariosyaccesosActionPerformed

    private void mnusalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnusalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnusalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itmnuclientes;
    private javax.swing.JMenuItem itmnuhabitaciones;
    private javax.swing.JMenuItem itmnupagos;
    private javax.swing.JMenuItem itmnuproductos;
    private javax.swing.JMenuItem itmnureservasyconsumos;
    private javax.swing.JMenuItem itmnuusuariosyaccesos;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JLabel lblacceso;
    public static javax.swing.JLabel lblamaterno;
    public static javax.swing.JLabel lblapaterno;
    public static javax.swing.JLabel lblidpersona;
    public static javax.swing.JLabel lblnombre;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu mnuarchivo;
    private javax.swing.JMenu mnuayuda;
    public static javax.swing.JMenu mnuconfiguraciones;
    private javax.swing.JMenu mnuconsultas;
    private javax.swing.JMenu mnuherramientas;
    private javax.swing.JMenu mnureservas;
    private javax.swing.JMenu mnusalir;
    private javax.swing.JMenu mnusisdenaf;
    // End of variables declaration//GEN-END:variables

}
